NCHARS = 5

IMAGE_HEIGHT = 60
IMAGE_WIDTH = 175

DEFAULT_DATASET_DIR = "data"
DEFAULT_MODEL_DIR = "model"
DEFAULT_GPU = -1

DEFAULT_GRIDS = ((6, 20), )
DEFAULT_ASPECT_RATIOS = ((1.5, 2), )
DEFAULT_VARIANCE = (0.1, 0.1)

DEFAULT_CHANNEL = 4
DEFAULT_OPTIMIZER = 'adam'
DEFAULT_ALPHA = 0.001
DEFAULT_EPOCH = 100
DEFAULT_BATCHSIZE = 32
DEFAULT_FREQUENCY = 10
DEFAULT_SCORE_THRESH = 0.1
DEFAULT_NMS_THRESH = 0.45

# constants.py
